on:
  push:
    branches:
      - main  # Certifique-se de que sua branch principal se chama 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Atualizado para v4

      - name: Setup Pages
        uses: actions/configure-pages@v4 # Atualizado para v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # Atualizado para v3 (versão estável atual)
        with:
          path: '.'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Atualizado para v4
